name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Java 8
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "8.0.292"

      - name: Verify Java installation
        run: java -version
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create allure-result directory
        run: mkdir -p allure/results

      - name: Create allure-report directory
        run: mkdir -p allure/report
      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
          tar -zxvf allure-2.13.8.tgz
          sudo mv allure-2.13.8 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          echo 'export PATH="/opt/allure/bin:$PATH"' >> $GITHUB_ENV
          allure --version
      - name: Run tests
        run: npm run test

      - name: Generate Allure report
        run: allure generate allure/results -o allure/report --clean

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure/report
          retention-days: 5

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        with:
          publish_dir: allure-report
          keep_files:
